export const GET_TRAILS_REQUEST = 'GET_TRAILS_REQUEST';
export const GET_TRAILS_SUCCESS = 'GET_TRAILS_SUCCESS';
export const GET_TRAILS_FAIL = 'GET_TRAILS_FAIL';

export const GET_TRAIL_DETAILS_REQUEST = 'GET_TRAIL_DETAILS_REQUEST';
export const GET_TRAIL_DETAILS_SUCCESS = 'GET_TRAIL_DETAILS_SUCCESS';
export const GET_TRAIL_DETAILS_FAIL = 'GET_TRAIL_DETAILS_FAIL';

export const TRAIL_CREATE_REQUEST = 'TRAIL_CREATE_REQUEST';
export const TRAIL_CREATE_SUCCESS = 'TRAIL_CREATE_SUCCESS';
export const TRAIL_CREATE_FAIL = 'TRAIL_CREATE_FAIL';

export const TRAIL_DELETE_REQUEST = 'TRAIL_DELETE_REQUEST';
export const TRAIL_DELETE_SUCCESS = 'TRAIL_DELETE_SUCCESS';
export const TRAIL_DELETE_FAIL = 'TRAIL_DELETE_FAIL';

// export const TRAIL_UPDATE_REQUEST = 'TRAIL_UPDATE_REQUEST';
// export const TRAIL_UPDATE_SUCCESS = 'TRAIL_UPDATE_SUCCESS';
// export const TRAIL_UPDATE_FAIL = 'TRAIL_UPDATE_FAIL';